# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('nombre_corto', models.CharField(max_length=16)),
                ('titulo', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Data_red_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_empleo', models.TextField()),
                ('lugar', models.CharField(max_length=100)),
                ('funciones_laborales', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('nivel_de_experiencia', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('tipo_empleo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Data red social',
                'verbose_name_plural': 'Data redes sociales',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Palabra_clave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Carrera')),
            ],
            options={
                'verbose_name': 'Palabra clave',
                'verbose_name_plural': 'Palabras claves',
            },
        ),
        migrations.CreateModel(
            name='Red_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Red_social'),
        ),
    ]
